{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.equo.ide",
    "module": "solstice",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "com.diffplug.durian",
          "module": "durian-swt.os",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.osgi",
          "version": {
            "requires": "3.18.300"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "solstice-1.3.1.jar",
          "url": "solstice-1.3.1.jar",
          "size": 399725,
          "sha512": "93a6dc07ce29578f9f3bf7839ca2e1390dff5408cd8af07d3b589ee93270548910319957fc574d3cb39ff9e31d94d423f2bdb03600c94afa797bdbbeb618c42f",
          "sha256": "765f5e10c748a1fa51cb7b6cc87f2982ab36b71597e69f709d98bf1136b5304f",
          "sha1": "b5963a147a89102535d8da66d53a8f1163c51b1d",
          "md5": "bfc25e482cd82204a2ba775ea36a3791"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.osgi",
          "version": {
            "requires": "3.18.300"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "com.diffplug.durian",
          "module": "durian-swt.os",
          "version": {
            "requires": "4.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "solstice-1.3.1.jar",
          "url": "solstice-1.3.1.jar",
          "size": 399725,
          "sha512": "93a6dc07ce29578f9f3bf7839ca2e1390dff5408cd8af07d3b589ee93270548910319957fc574d3cb39ff9e31d94d423f2bdb03600c94afa797bdbbeb618c42f",
          "sha256": "765f5e10c748a1fa51cb7b6cc87f2982ab36b71597e69f709d98bf1136b5304f",
          "sha1": "b5963a147a89102535d8da66d53a8f1163c51b1d",
          "md5": "bfc25e482cd82204a2ba775ea36a3791"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "solstice-1.3.1-javadoc.jar",
          "url": "solstice-1.3.1-javadoc.jar",
          "size": 505924,
          "sha512": "5f70c1e5e6f05885670ff2570e5b0dcf6b0860a02eaef67f7148ec06b3db24069ee369e179c1407cda2575a055e492d589690b51f100a7266ff83adc31184909",
          "sha256": "9b3c272e8c49fd5ad1d25f0b714bc689c0f7c9a69e1f533ef2e65ded9461244f",
          "sha1": "e6da74dbf4abd3474686434454638a1193fbaa9b",
          "md5": "938a49bd0c942fda24e262ef668113dd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "solstice-1.3.1-sources.jar",
          "url": "solstice-1.3.1-sources.jar",
          "size": 220755,
          "sha512": "3e9e2bded92a1429e0a5fd983a99adb42b510c6b721d8f1777c6bafa739e05f6f702ee5ee5320859dcb66253e0e24557af0365787965cc8d4e6677086854d928",
          "sha256": "d7a194b8b5120d7e4d8529d3358a598c53f97ea428a63e463a0a226ba60605ec",
          "sha1": "cdb9ed02097c2275c90fc2c6fb4ecf32188cdf52",
          "md5": "6a01693964e40a0ea5e6de9235305b34"
        }
      ]
    }
  ]
}
