{
  "formatVersion": "1.1",
  "component": {
    "group": "com.diffplug.spotless",
    "module": "spotless-lib-extra",
    "version": "2.40.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-lib",
          "version": {
            "requires": "2.40.0"
          }
        }
      ],
      "files": [
        {
          "name": "spotless-lib-extra-2.40.0.jar",
          "url": "spotless-lib-extra-2.40.0.jar",
          "size": 76030,
          "sha512": "6202195312867b8f030970bfa705d6531f9c8f61b5de8d97a4556fafe94aa23cf8d45c4770befd44b41212998bee6ae8c00673facbf42b937174a3d4385d19f5",
          "sha256": "ffe34464ed38737d8c990f889b9d5bf3b6fec2fbbea00bd4abdd928ee34f5316",
          "sha1": "7a252b8c02c38452f9f3be03dd1fc1937c630dd5",
          "md5": "e77b58eb439fbee98e66c5d376d949fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.diffplug.durian",
          "module": "durian-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.diffplug.durian",
          "module": "durian-collect",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.6.0.202305301015-r"
          }
        },
        {
          "group": "com.googlecode.concurrent-trees",
          "module": "concurrent-trees",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "dev.equo.ide",
          "module": "solstice",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-lib",
          "version": {
            "requires": "2.40.0"
          }
        }
      ],
      "files": [
        {
          "name": "spotless-lib-extra-2.40.0.jar",
          "url": "spotless-lib-extra-2.40.0.jar",
          "size": 76030,
          "sha512": "6202195312867b8f030970bfa705d6531f9c8f61b5de8d97a4556fafe94aa23cf8d45c4770befd44b41212998bee6ae8c00673facbf42b937174a3d4385d19f5",
          "sha256": "ffe34464ed38737d8c990f889b9d5bf3b6fec2fbbea00bd4abdd928ee34f5316",
          "sha1": "7a252b8c02c38452f9f3be03dd1fc1937c630dd5",
          "md5": "e77b58eb439fbee98e66c5d376d949fe"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotless-lib-extra-2.40.0-javadoc.jar",
          "url": "spotless-lib-extra-2.40.0-javadoc.jar",
          "size": 348888,
          "sha512": "c12b0b0bc1c9615f875340968325c6dea48c3b9f5a8b00fd0bcdc29742ceb962ab365e28f439fdff35deb1399e594ae0dfad151c4e69d043b594c4c11e2c49dd",
          "sha256": "68d328c58adbfd8f06ee001420e61da598c83f094494899ba411cf70cbe2d687",
          "sha1": "21f8cad90f074036a7dc96acd7e5936c52244a70",
          "md5": "6895383109b2e04c01d7d358e158cde0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotless-lib-extra-2.40.0-sources.jar",
          "url": "spotless-lib-extra-2.40.0-sources.jar",
          "size": 38306,
          "sha512": "d9ad47962212b6ceda71dedd94bc06ef84aa39681b4fd6c34a8b0b99cc5951d4df21ee4d5590b1565336282a687afcb23cb6e651717d1eeaa0164291bcf68254",
          "sha256": "c07a6ef9295d0e309dadb1d3cbc618f7ebc63b4e419c5aa532389fe86d58be02",
          "sha1": "e7c8abb15b42ce59423c1a513ec25cba16074bde",
          "md5": "300147617fb1348191ca3d3a9e0cdd0c"
        }
      ]
    }
  ]
}
